version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: mautic_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mauticdb
      MYSQL_USER: mautic
      MYSQL_PASSWORD: mautic
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  mautic:
    build: .
    ports:
      - "8080:80"
    environment:
      MAUTIC_DB_HOST: db
      MAUTIC_DB_PORT: 3306
      MAUTIC_DB_USER: mautic
      MAUTIC_DB_PASSWORD: mautic
      MAUTIC_DB_NAME: mauticdb
      MAUTIC_TRUSTED_PROXIES: '["0.0.0.0/0"]'
      MAUTIC_RUN_CRON_JOBS: 'true'
      PHP_INI_DATE_TIMEZONE: 'UTC'
    depends_on:
      - db
    volumes:
      - mautic_data:/var/www/html/var

volumes:
  db_data:
  mautic_data: